### ISSUE TITLE
I'm lost on this. My only guess is ubuntu doesn't like the updates.

### ISSUE THREAD

**Issue by Masterskitz** [Warcraft-GO-Team/Warcraft-GO#26]
Been running a cs:go servers for a while now, and I saw that the WCS crew have released a beta for WCGO (which is a must have). Upon adding python, easyplayer and wcgo to my server, this is the error it gets and cant get past. Please someone let me know where I'm going wrong with this.

[Source.Python] Loading...
Traceback (most recent call last):
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/__init__.py", line 42, in load
    setup_logging()
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/__init__.py", line 85, in setup_logging
    from core.settings import _core_settings
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/core/settings.py", line 15, in <module>
    from auth.paths import AUTH_PROVIDER_PATH
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/auth/__init__.py", line 12, in <module>
    from translations.strings import LangStrings
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/translations/strings.py", line 10, in <module>
    from binascii import unhexlify
ImportError: libz.so.1: cannot open shared object file: No such file or directory
[Source.Python] Failed to load the main module.
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
Traceback (most recent call last):
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/__init__.py", line 56, in unload
    unload_plugins()
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/__init__.py", line 250, in unload_plugins
    from core.manager import core_plugin_manager
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/core/manager.py", line 12, in <module>
    from plugins.manager import PluginManager
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/plugins/__init__.py", line 12, in <module>
    from translations.strings import LangStrings
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/translations/strings.py", line 10, in <module>
    from binascii import unhexlify
ImportError: libz.so.1: cannot open shared object file: No such file or directory
[Source.Python] Failed to unload the main module.
[Source.Python] Unloaded successfully.

This all runs fine on windows based servers. Has anyone had luck getting it to work on a ubuntu server ?

I'm running a Ubuntu 15 server, 16g ram. All the game files have full read/write/exe permissions.

**Comment by Mahi** [comment]
I believe this is Source.Python's issue, not ours. Seems like you've already posted it there, so wait for their answer :)
